[package]
name = "unified_sim_model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.3"
tracing = "0.1.37"
thiserror = "1.0.40"

[dev-dependencies]
tracing-subscriber = "0.3.17"